import React from 'react';
import ReactMarkdown from 'react-markdown';
import { SearchResult } from '../types';
import { SourcesList } from './SourcesList';

interface PrintableReportProps {
  id?: string;
  data: SearchResult | null;
  config: {
    infographic: boolean;
    analysis: boolean;
    tradePlan: boolean;
    sources: boolean;
  };
  query: string;
}

// Helper to split text
const getReportContent = (fullText: string) => {
  const splitIndex = fullText.indexOf('## Part 2');
  if (splitIndex !== -1) {
    return {
      part1: fullText.substring(0, splitIndex),
      part2: fullText.substring(splitIndex)
    };
  }
  return { part1: fullText, part2: '' };
};

export const PrintableReport: React.FC<PrintableReportProps> = ({ id, data, config, query }) => {
  if (!data) {
    return <div id={id} style={{ color: 'red', padding: '20px' }}>Error: No Data Available to Print</div>;
  }

  const { part1, part2 } = getReportContent(data.text || '');
  const info = data.infographic;

  // STRICT "Safe Mode" Styles
  // No flexbox, no grid, no absolute positioning. 
  // Standard document flow only.
  const containerStyle: React.CSSProperties = {
    fontFamily: 'Helvetica, Arial, sans-serif',
    color: '#000000',
    backgroundColor: '#ffffff',
    padding: '40px', // Approx 1 inch margin
    width: '100%',
    boxSizing: 'border-box',
    lineHeight: '1.5',
  };

  const titleStyle: React.CSSProperties = {
    fontSize: '28px',
    fontWeight: 'bold',
    marginBottom: '5px',
    borderBottom: '2px solid #000',
    paddingBottom: '15px',
    textTransform: 'uppercase',
  };

  const metaStyle: React.CSSProperties = {
    fontSize: '12px',
    color: '#444',
    marginBottom: '30px',
  };

  const sectionHeaderStyle: React.CSSProperties = {
    fontSize: '20px',
    fontWeight: 'bold',
    marginTop: '30px',
    marginBottom: '15px',
    textTransform: 'uppercase',
    borderBottom: '1px solid #ccc',
    paddingBottom: '5px',
  };

  const listStyle: React.CSSProperties = {
    listStyleType: 'disc',
    paddingLeft: '20px',
    marginBottom: '20px',
  };

  const listItemStyle: React.CSSProperties = {
    marginBottom: '8px',
  };

  return (
    <div id={id} style={containerStyle}>
      {/* 1. Header */}
      <h1 style={titleStyle}>{query.toUpperCase()} - EARNINGS REPORT</h1>
      <p style={metaStyle}>
        Generated by Earnings Scout | {new Date().toLocaleDateString()}
      </p>

      {/* 2. Executive Summary (Replacing Graphic Cards) */}
      {config.infographic && info && (
        <div>
          <h2 style={sectionHeaderStyle}>1. Executive Summary</h2>
          <ul style={listStyle}>
            <li style={listItemStyle}>
              <strong>CEO Vibe Score:</strong> {info.vibe.score}/10
            </li>
            <li style={listItemStyle}>
              <strong>Analysis:</strong> {info.vibe.analysis}
            </li>
            <li style={listItemStyle}>
              <strong>CEO Quote:</strong> "{info.vibe.quote}"
            </li>
            <li style={listItemStyle}>
              <strong>Consensus Rating:</strong> {info.consensus.rating}
            </li>
            <li style={listItemStyle}>
              <strong>Price Target:</strong> {info.consensus.priceTarget}
            </li>
            <li style={listItemStyle}>
              <strong>Catalyst (Green Flag):</strong> {info.greenFlag.title} - {info.greenFlag.description}
            </li>
            <li style={listItemStyle}>
              <strong>Risk (Red Flag):</strong> {info.redFlag.title} - {info.redFlag.description}
            </li>
          </ul>
        </div>
      )}

      {/* 3. Analysis (Markdown -> Simple HTML) */}
      {config.analysis && part1 && (
        <div>
          <h2 style={sectionHeaderStyle}>2. Detailed Analysis</h2>
          <ReactMarkdown
            components={{
              h1: ({node, ...props}) => <h3 style={{ fontSize: '18px', fontWeight: 'bold', marginTop: '20px', marginBottom: '10px' }} {...props} />,
              h2: ({node, ...props}) => <h4 style={{ fontSize: '16px', fontWeight: 'bold', marginTop: '15px', marginBottom: '8px' }} {...props} />,
              h3: ({node, ...props}) => <strong style={{ display: 'block', marginTop: '10px', marginBottom: '5px' }} {...props} />,
              p: ({node, ...props}) => <p style={{ marginBottom: '12px' }} {...props} />,
              ul: ({node, ...props}) => <ul style={{ listStyleType: 'disc', paddingLeft: '20px', marginBottom: '12px' }} {...props} />,
              ol: ({node, ...props}) => <ol style={{ listStyleType: 'decimal', paddingLeft: '20px', marginBottom: '12px' }} {...props} />,
              li: ({node, ...props}) => <li style={{ marginBottom: '4px' }} {...props} />,
              blockquote: ({node, ...props}) => <blockquote style={{ borderLeft: '4px solid #ccc', paddingLeft: '10px', marginLeft: '0', fontStyle: 'italic' }} {...props} />,
            }}
          >
            {part1}
          </ReactMarkdown>
        </div>
      )}

      {/* 4. Trade Plan */}
      {config.tradePlan && part2 && (
        <div>
           <h2 style={sectionHeaderStyle}>3. Strategic Trade Plan</h2>
           <ReactMarkdown
            components={{
              h1: ({node, ...props}) => <h3 style={{ fontSize: '18px', fontWeight: 'bold', marginTop: '20px', marginBottom: '10px' }} {...props} />,
              h2: ({node, ...props}) => <h4 style={{ fontSize: '16px', fontWeight: 'bold', marginTop: '15px', marginBottom: '8px' }} {...props} />,
              h3: ({node, ...props}) => <strong style={{ display: 'block', marginTop: '10px', marginBottom: '5px' }} {...props} />,
              p: ({node, ...props}) => <p style={{ marginBottom: '12px' }} {...props} />,
              ul: ({node, ...props}) => <ul style={{ listStyleType: 'disc', paddingLeft: '20px', marginBottom: '12px' }} {...props} />,
              ol: ({node, ...props}) => <ol style={{ listStyleType: 'decimal', paddingLeft: '20px', marginBottom: '12px' }} {...props} />,
              li: ({node, ...props}) => <li style={{ marginBottom: '4px' }} {...props} />,
            }}
          >
            {part2}
          </ReactMarkdown>
        </div>
      )}

      {/* 5. Sources */}
      {config.sources && (
        <div style={{ marginTop: '40px', paddingTop: '20px', borderTop: '1px solid #000' }}>
          <h3 style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '10px' }}>Sources</h3>
          {/* We reuse SourcesList but it might output stylized HTML. 
              Ideally we should use a simpler version, but the 'list' variant is mostly UL/LI.
          */}
          <SourcesList metadata={data.groundingMetadata} variant="list" />
        </div>
      )}
    </div>
  );
};